# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-18.04

steps:
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-X'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: default
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'clean install'
