# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-18.04

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world' &&\
      cat /etc/os-release && \
      cd /opt && \
      ls && \
      wget --version && \
      wget https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz && \
      ls && \
      tar -zxvf apache-maven-3.8.4-bin.tar.gz && \
      mv apache-maven-3.8.4 maven && \
      export PATH=$PATH:/opt/maven/bin && \
      cd /opt && \
      ls && \
      wget -c https://github.com/elzerver/WebGoat/archive/refs/heads/develop.zip && \
      unzip develop.zip && \
      ls -ltra && \
      cd WebGoat-develop && \
      mvn clean package 

